const SCREENS = {
  INITIAL: 'InitialScreen',
  LOGIN: 'Login',
  FORGOT_PASSWORD: 'Forgot Password',
  FILTER: 'Filter',
  CONFIRM_PRODUCT: 'ConfirmProduct',
  ORDER_CONFIRMED: 'OrderConfirmed',
  SHIPPING_ADDRESS_DETAILS: 'SHIPPING ADDRESS',
  NEW_SHIPPING_ADDRESS: 'New Shipping Address',
  SEARCH_COLLECTION: 'SearchCollection',
  SIGNUP: 'SignUp',
  PRODUCT: 'Product',
  TERMS_OF_SERVICE: 'TermsOfService',
  HOME: 'Home',
  BOTTOM_TAB_NAVIGATOR: 'BottomTabNavigator',
  ACCOUNT_SETTINGS: 'AccountSettings',
  PROFILE: 'SETTINGS',
  ORDERS_HISTORY: 'YOUR ORDERS',
  SUPPORT: 'SUPPORT',
  TERMS: 'RIF TERMS AND CONDITIONS',
  PRIVACY: 'RIF PRIVACY POLICY',
  CATEGORY_SECTION: 'CategorySection',
  SIZES_SECTION: 'SizeSection',
  SORTBY_SECTION: 'SortBySection',
  MOST_POPULAR: 'Most Popular Collection',
  NEW: 'New Collection',
  LOWEST_PRICE_PRODUCTS: 'Lowest Price Collection',
  HIGHEST_PRICE_PRODUCTS: 'Highest Price Collection',
  CHECKOUT: 'Place Order',
  CART: 'Cart',
};

export default SCREENS;
